name: Daily Schedule
on:
  schedule:
    # 配置CRON表达式，每天运行一次，这里设置为每天的0点
    - cron: '40 6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # 根据你的脚本需求设置Python版本
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # 如果你的脚本有依赖，请列出在requirements.txt文件中
        
    - name: Run my script
      run: |
        python storyTeller.py # 替换为你的Python脚本文件名
        
    - name: Commit and push if stories.csv has changed
      run: |
        # 使用 git diff 检查 stories.csv 是否有更改
        if git diff --quiet stories.csv; then
          echo "No changes detected in stories.csv"
        else
          # Add the changed file to staging area
          git add stories.csv
          # Commit the changes with a message
          git commit -m "Update stories.csv with new story" --author="GitHub Actions <actions@github.com>"
          # Push the changes to the branch
          git push
          echo "Changes have been committed and pushed."
        fi
